const menu = [
  {
    id: 1,
    title: 'virat kohli',
    category: 'batsman',
    rank: 1,
    img: 'https://wikibio.in/wp-content/uploads/2018/07/Virat-Kohali-1280x720.jpg',
    desc: `The elegant right hand batter and a former indian cricket team captain `,
  },
  {
    id: 2,
    title: 'ms dhoni',
    category: 'batsman',
    rank: 7,
    img: 'https://images.mid-day.com/images/images/2021/jul/dhoni-july-seven_d.jpg',
    desc: `hard hitting wicket keeping batsman hails from ranchi , known for his captaincy and his helicopter shots `,
  },
  {
    id: 3,
    title: 'ravi jadeja',
    category: 'all-rounder',
    rank: 10,
    img: 'https://img.republicworld.com/republic-prod/stories/promolarge/xhdpi/uslunzmk2bquki1s_1645601203.jpeg',
    desc: ` uber cool all rounder who can swing his bat for sixes , has a nick name of sir`,
  },
  {
    id: 4,
    title: 'ben stokes',
    category: 'all-rounder',
    rank: 9,
    img: 'https://resources.ecb.co.uk/photo-resources/2022/04/28/978ab167-e3ff-428c-ad47-9ba5c18a9a52/OUTFIT-9_BEN-STOKES_938.jpg?width=896&height=504',
    desc: `all the way from newzealand to represent england cricket team,a hard hitting middle order batsman `,
  },
  {
    id: 5,
    title: 'dale steyn',
    category: 'bowler',
    rank: 5,
    img: 'https://i.dawn.com/primary/2021/08/612e0e70c2b78.jpg',
    desc: `a fiercy fast bowler who can destroy the defense of the batsman`,
  },
  {
    id: 6,
    title: 'jasprit bumrah',
    category: 'bowler',
    rank: 4,
    img: 'https://e1.365dm.com/21/02/768x432/skysports-jasprit-bumrah-bumrah_5286477.jpg?20210227083253',
    desc: `from gujurat a fast bowler from india whom we can trust `,
  },
  {
    id: 7,
    title: 'umran malik',
    category: 'bowler',
    rank: 99,
    img: 'https://c.ndtvimg.com/2022-06/voa7iopg_umran-malik-twitter_625x300_16_June_22.jpg',
    desc: `from the hills of jammu,a super quick fast bowler who can bowl 150kmps`,
  },
  {
    id: 8,
    title: 'jason holder',
    category: 'all-rounder',
    rank: 25,
    img: 'https://resize.indiatvnews.com/en/resize/newbucket/715_-/2019/08/ap19234583897210-1566719064.jpg',
    desc: `a 7ft carribean fast bowling all rounder who can bat`,
  },
  {
    id: 9,
    title: 'rohit sharma',
    category: 'batsman',
    rank: 14,
    img: 'https://img.onmanorama.com/content/dam/mm/en/sports/cricket/images/2022/2/10/rohit.jpg',
    desc: `a stylish opening batsman from the maidans of mumbai`,
  },
];
export default menu;